### ISSUE TITLE
[REQUEST] Add button for direct APK download

### ISSUE THREAD

**Issue by esQmo** [michaldrabik/showly-website#13]
Hello @michaldrabik could it be possible to add a direct download button for APK files? Some users could not have PlayStore installed, such as Huawei owners. So I thought having such feature would be awesome. 

Keep up with your great works.

**Comment by michaldrabik** [comment]
I'm going to start posting them under Releases: https://github.com/michaldrabik/showly-2.0/releases/tag/2.8.0

Just a note - they are not signed with GooglePlay so you won't be able to install them as an update to existing Play Store version and vice versa.
